server:
  port: 9001
spring:
  application:
    name: configServerBus
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LTai123456/springCloud-Configer/    # 配置git仓库的地址
          search-paths:                              # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                         # git仓库的账号
          password:                                     # git仓库的密码
          default-label: master
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/   ## 注册中心eurka地址
management:
  security:
     enabled: false