eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/
  instance:
    appname: feign-hystrix-client

server:
  port: 8087

spring:
  application:
    name: feign-hystrix-client
feign:
  hystrix:
    enabled: true